# Generated by Django 4.2.7 on 2025-11-03 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_management', '0003_remove_auditlog_idx_log_user_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本消息'), ('textcard', '文本卡片'), ('markdown', 'Markdown')], max_length=20, verbose_name='消息类型')),
                ('to_users', models.JSONField(default=list, verbose_name='接收用户列表')),
                ('to_departments', models.JSONField(default=list, verbose_name='接收部门列表')),
                ('to_tags', models.JSONField(default=list, verbose_name='接收标签列表')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('url', models.URLField(blank=True, verbose_name='跳转链接')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('wechat_msg_id', models.CharField(blank=True, max_length=100, verbose_name='企微消息ID')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('business_type', models.CharField(blank=True, max_length=50, verbose_name='业务类型')),
                ('business_id', models.BigIntegerField(blank=True, null=True, verbose_name='业务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '企微消息',
                'verbose_name_plural': '企微消息',
                'db_table': 'wechat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_wechat_msg_status'), models.Index(fields=['business_type', 'business_id'], name='idx_wechat_msg_business'), models.Index(fields=['created_at'], name='idx_wechat_msg_time')],
            },
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_user_id', models.CharField(max_length=64, unique=True, verbose_name='企微用户ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户姓名')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('department_ids', models.JSONField(default=list, verbose_name='部门ID列表')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('0', '未定义')], default='0', max_length=10, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('avatar', models.URLField(blank=True, verbose_name='头像URL')),
                ('status', models.IntegerField(choices=[(1, '已激活'), (2, '已禁用'), (4, '未激活'), (5, '退出企业')], default=1, verbose_name='账号状态')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('failed', '同步失败')], default='pending', max_length=20, verbose_name='同步状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('local_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_user', to=settings.AUTH_USER_MODEL, verbose_name='本地用户')),
            ],
            options={
                'verbose_name': '企微用户',
                'verbose_name_plural': '企微用户',
                'db_table': 'wechat_user',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['wechat_user_id'], name='idx_wechat_user_id'), models.Index(fields=['sync_status'], name='idx_wechat_user_sync'), models.Index(fields=['mobile'], name='idx_wechat_user_mobile')],
            },
        ),
        migrations.CreateModel(
            name='WechatSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('department', '部门同步'), ('user', '用户同步'), ('full', '全量同步')], max_length=20, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('running', '同步中'), ('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='同步状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数量')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('details', models.JSONField(default=dict, verbose_name='同步详情')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
            ],
            options={
                'verbose_name': '企微同步日志',
                'verbose_name_plural': '企微同步日志',
                'db_table': 'wechat_sync_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type'], name='idx_wechat_sync_type'), models.Index(fields=['status'], name='idx_wechat_sync_status'), models.Index(fields=['started_at'], name='idx_wechat_sync_time')],
            },
        ),
        migrations.CreateModel(
            name='WechatDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_dept_id', models.BigIntegerField(unique=True, verbose_name='企微部门ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='上级部门ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('failed', '同步失败')], default='pending', max_length=20, verbose_name='同步状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('local_department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_department', to='system_management.department', verbose_name='本地部门')),
            ],
            options={
                'verbose_name': '企微部门',
                'verbose_name_plural': '企微部门',
                'db_table': 'wechat_department',
                'ordering': ['order', 'wechat_dept_id'],
                'indexes': [models.Index(fields=['wechat_dept_id'], name='idx_wechat_dept_id'), models.Index(fields=['sync_status'], name='idx_wechat_dept_sync')],
            },
        ),
    ]
