# Generated by Django 4.2.7 on 2025-11-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_optimize_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_log_user_time',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_log_action_time',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_log_target_time',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='idx_dept_parent_order',
        ),
        migrations.RemoveIndex(
            model_name='permission',
            name='idx_perm_module_code',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='idx_role_active_time',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_dept_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_active_time',
        ),
    ]
