# Generated by Django 4.2.7 on 2025-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0003_remove_auditlog_idx_log_user_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechat_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='企微用户ID'),
        ),
    ]
