# Generated by Django 4.2.7 on 2025-11-03 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='实例ID')),
                ('instance_no', models.CharField(max_length=50, unique=True, verbose_name='审批单号')),
                ('title', models.CharField(max_length=200, verbose_name='审批标题')),
                ('form_data', models.JSONField(verbose_name='表单数据')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('business_id', models.IntegerField(verbose_name='业务ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('in_progress', '审批中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('withdrawn', '已撤销')], default='pending', max_length=20, verbose_name='审批状态')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('final_result', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '拒绝'), ('withdrawn', '撤销')], max_length=20, null=True, verbose_name='最终结果')),
            ],
            options={
                'verbose_name': '审批实例',
                'verbose_name_plural': '审批实例',
                'db_table': 'approval_instance',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='节点ID')),
                ('node_name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('approval', '审批节点'), ('cc', '抄送节点'), ('condition', '条件节点')], default='approval', max_length=20, verbose_name='节点类型')),
                ('sequence', models.IntegerField(verbose_name='节点序号')),
                ('approver_config', models.JSONField(verbose_name='审批人配置')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='节点状态')),
                ('approval_result', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '拒绝'), ('transferred', '转交'), ('added_sign', '加签')], max_length=20, null=True, verbose_name='审批结果')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='approval.approvalinstance', verbose_name='审批实例')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'db_table': 'approval_node',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='模板ID')),
                ('template_code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('template_name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(verbose_name='模板描述')),
                ('form_schema', models.JSONField(verbose_name='表单配置')),
                ('flow_config', models.JSONField(verbose_name='流程配置')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批模板',
                'verbose_name_plural': '审批模板',
                'db_table': 'approval_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalNodeCC',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_users', to='approval.approvalnode', verbose_name='审批节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_nodes', to=settings.AUTH_USER_MODEL, verbose_name='抄送人')),
            ],
            options={
                'verbose_name': '审批节点抄送人',
                'verbose_name_plural': '审批节点抄送人',
                'db_table': 'approval_node_cc',
            },
        ),
        migrations.CreateModel(
            name='ApprovalNodeApprover',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approval.approvalnode', verbose_name='审批节点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '审批节点审批人',
                'verbose_name_plural': '审批节点审批人',
                'db_table': 'approval_node_approver',
            },
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='approval.approvalnode', verbose_name='当前节点'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_approvals', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approval.approvaltemplate', verbose_name='审批模板'),
        ),
        migrations.CreateModel(
            name='ApprovalFollow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='关注ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='approval.approvalinstance', verbose_name='审批实例')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_approvals', to=settings.AUTH_USER_MODEL, verbose_name='关注人')),
            ],
            options={
                'verbose_name': '审批关注',
                'verbose_name_plural': '审批关注',
                'db_table': 'approval_follow',
            },
        ),
        migrations.CreateModel(
            name='ApprovalComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='approval.approvalinstance', verbose_name='审批实例')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '审批评论',
                'verbose_name_plural': '审批评论',
                'db_table': 'approval_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvaltemplate',
            index=models.Index(fields=['template_code'], name='idx_appr_tmpl_code'),
        ),
        migrations.AddIndex(
            model_name='approvaltemplate',
            index=models.Index(fields=['status'], name='idx_appr_tmpl_status'),
        ),
        migrations.AddIndex(
            model_name='approvalnodecc',
            index=models.Index(fields=['node'], name='idx_appr_node_cc_node'),
        ),
        migrations.AddIndex(
            model_name='approvalnodecc',
            index=models.Index(fields=['user'], name='idx_appr_node_cc_user'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalnodecc',
            unique_together={('node', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalnodeapprover',
            index=models.Index(fields=['node'], name='idx_appr_node_appr_node'),
        ),
        migrations.AddIndex(
            model_name='approvalnodeapprover',
            index=models.Index(fields=['user'], name='idx_appr_node_appr_user'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalnodeapprover',
            unique_together={('node', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['instance', 'sequence'], name='idx_appr_node_seq'),
        ),
        migrations.AddIndex(
            model_name='approvalnode',
            index=models.Index(fields=['status'], name='idx_appr_node_status'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['instance_no'], name='idx_appr_inst_no'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['status'], name='idx_appr_inst_status'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['business_type', 'business_id'], name='idx_appr_business'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['initiator'], name='idx_appr_initiator'),
        ),
        migrations.AddIndex(
            model_name='approvalfollow',
            index=models.Index(fields=['user'], name='idx_appr_follow_user'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalfollow',
            unique_together={('instance', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalcomment',
            index=models.Index(fields=['instance'], name='idx_appr_comment_inst'),
        ),
        migrations.AddIndex(
            model_name='approvalcomment',
            index=models.Index(fields=['user'], name='idx_appr_comment_user'),
        ),
    ]
