# Generated by Django 4.2.7 on 2025-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planapproval',
            name='unique_pending_approval',
        ),
        migrations.RemoveConstraint(
            model_name='regionalplan',
            name='unique_plan_region_store_type',
        ),
        migrations.RemoveConstraint(
            model_name='regionalplan',
            name='valid_regional_target_count',
        ),
        migrations.RemoveConstraint(
            model_name='regionalplan',
            name='valid_regional_completed_count',
        ),
        migrations.RemoveConstraint(
            model_name='storeplan',
            name='valid_date_range',
        ),
        migrations.RemoveConstraint(
            model_name='storeplan',
            name='valid_target_count',
        ),
        migrations.RemoveConstraint(
            model_name='storeplan',
            name='valid_completed_count',
        ),
        migrations.RemoveIndex(
            model_name='businessregion',
            name='idx_region_code',
        ),
        migrations.RemoveIndex(
            model_name='businessregion',
            name='idx_region_active',
        ),
        migrations.RemoveIndex(
            model_name='planapproval',
            name='idx_approval_plan',
        ),
        migrations.RemoveIndex(
            model_name='planapproval',
            name='idx_approval_status',
        ),
        migrations.RemoveIndex(
            model_name='planapproval',
            name='idx_approval_type',
        ),
        migrations.RemoveIndex(
            model_name='planapproval',
            name='idx_approval_submitted',
        ),
        migrations.RemoveIndex(
            model_name='planexecutionlog',
            name='idx_execution_log_plan',
        ),
        migrations.RemoveIndex(
            model_name='planexecutionlog',
            name='idx_execution_log_regional',
        ),
        migrations.RemoveIndex(
            model_name='planexecutionlog',
            name='idx_execution_log_action',
        ),
        migrations.RemoveIndex(
            model_name='planexecutionlog',
            name='idx_execution_log_date',
        ),
        migrations.RemoveIndex(
            model_name='planexecutionlog',
            name='idx_execution_log_store',
        ),
        migrations.RemoveIndex(
            model_name='regionalplan',
            name='idx_regional_plan_plan',
        ),
        migrations.RemoveIndex(
            model_name='regionalplan',
            name='idx_regional_plan_region',
        ),
        migrations.RemoveIndex(
            model_name='regionalplan',
            name='idx_regional_plan_store_type',
        ),
        migrations.RemoveIndex(
            model_name='storeplan',
            name='idx_plan_status',
        ),
        migrations.RemoveIndex(
            model_name='storeplan',
            name='idx_plan_dates',
        ),
        migrations.RemoveIndex(
            model_name='storeplan',
            name='idx_plan_created_by',
        ),
        migrations.RemoveIndex(
            model_name='storeplan',
            name='idx_plan_type',
        ),
        migrations.RemoveIndex(
            model_name='storeplan',
            name='idx_plan_created_at',
        ),
        migrations.RemoveIndex(
            model_name='storetype',
            name='idx_store_type_code',
        ),
        migrations.RemoveIndex(
            model_name='storetype',
            name='idx_store_type_active',
        ),
        migrations.AlterField(
            model_name='businessregion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planexecutionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regionalplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='planapproval',
            unique_together={('plan', 'approval_type')},
        ),
        migrations.AlterUniqueTogether(
            name='regionalplan',
            unique_together={('plan', 'region', 'store_type')},
        ),
    ]
