# Generated by Django 4.2.7 on 2025-11-04 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='缓存键')),
                ('cache_data', models.JSONField(verbose_name='缓存数据')),
                ('cache_type', models.CharField(choices=[('dashboard', '经营大屏'), ('store_map', '开店地图'), ('funnel', '跟进漏斗'), ('plan_progress', '计划进度'), ('report_data', '报表数据')], max_length=50, verbose_name='缓存类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '数据分析缓存',
                'verbose_name_plural': '数据分析缓存',
                'db_table': 'analytics_cache',
                'indexes': [models.Index(fields=['cache_type', 'expires_at'], name='analytics_c_cache_t_3743ea_idx'), models.Index(fields=['cache_key'], name='analytics_c_cache_k_e23405_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('report_type', models.CharField(choices=[('plan', '开店计划报表'), ('follow_up', '拓店跟进进度报表'), ('preparation', '筹备进度报表'), ('assets', '门店资产报表')], max_length=50, verbose_name='报表类型')),
                ('filters', models.JSONField(default=dict, verbose_name='筛选条件')),
                ('format', models.CharField(choices=[('excel', 'Excel格式'), ('pdf', 'PDF格式')], default='excel', max_length=10, verbose_name='导出格式')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报表任务',
                'verbose_name_plural': '报表任务',
                'db_table': 'report_tasks',
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='report_task_created_6372f6_idx'), models.Index(fields=['status', 'created_at'], name='report_task_status_85efee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(verbose_name='数据日期')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='日营业额')),
                ('daily_orders', models.IntegerField(default=0, verbose_name='日订单数')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月营业额')),
                ('monthly_orders', models.IntegerField(default=0, verbose_name='月订单数')),
                ('data_source', models.CharField(default='external_api', max_length=100, verbose_name='数据来源')),
                ('sync_status', models.CharField(default='success', max_length=20, verbose_name='同步状态')),
                ('sync_message', models.TextField(blank=True, verbose_name='同步信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='store_archive.storeprofile', verbose_name='门店')),
            ],
            options={
                'verbose_name': '外部销售数据',
                'verbose_name_plural': '外部销售数据',
                'db_table': 'external_sales_data',
                'indexes': [models.Index(fields=['store', 'data_date'], name='external_sa_store_i_61a001_idx'), models.Index(fields=['data_date'], name='external_sa_data_da_e9fd5a_idx'), models.Index(fields=['sync_status'], name='external_sa_sync_st_3583ac_idx')],
                'unique_together': {('store', 'data_date')},
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('sales_data', '销售数据同步'), ('cache_refresh', '缓存刷新'), ('report_generation', '报表生成')], max_length=50, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='同步状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('records_processed', models.IntegerField(default=0, verbose_name='处理记录数')),
                ('records_success', models.IntegerField(default=0, verbose_name='成功记录数')),
                ('records_failed', models.IntegerField(default=0, verbose_name='失败记录数')),
                ('error_details', models.JSONField(default=dict, verbose_name='错误详情')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '数据同步日志',
                'verbose_name_plural': '数据同步日志',
                'db_table': 'data_sync_logs',
                'indexes': [models.Index(fields=['sync_type', 'start_time'], name='data_sync_l_sync_ty_5995e9_idx'), models.Index(fields=['status', 'start_time'], name='data_sync_l_status_4825d4_idx')],
            },
        ),
    ]
