# Generated by Django 4.2.7 on 2025-11-04 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasynclog',
            name='sync_type',
            field=models.CharField(choices=[('sales_data', '销售数据同步'), ('cache_refresh', '缓存刷新'), ('report_generation', '报表生成'), ('scheduled_report', '定时报表生成')], max_length=50, verbose_name='同步类型'),
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('report_type', models.CharField(choices=[('plan', '开店计划报表'), ('follow_up', '拓店跟进进度报表'), ('preparation', '筹备进度报表'), ('assets', '门店资产报表')], max_length=50, verbose_name='报表类型')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], max_length=20, verbose_name='生成频率')),
                ('filters', models.JSONField(default=dict, verbose_name='筛选条件')),
                ('format', models.CharField(choices=[('excel', 'Excel格式'), ('pdf', 'PDF格式')], default='excel', max_length=10, verbose_name='导出格式')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人邮箱列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='最后生成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '定时报表',
                'verbose_name_plural': '定时报表',
                'db_table': 'scheduled_reports',
                'indexes': [models.Index(fields=['is_active', 'frequency'], name='scheduled_r_is_acti_2488f3_idx'), models.Index(fields=['created_by'], name='scheduled_r_created_481947_idx')],
            },
        ),
    ]
