# Generated by Django 4.2.7 on 2025-11-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0002_alter_datasynclog_sync_type_scheduledreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsalesdata',
            name='average_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客单价'),
        ),
        migrations.AddField(
            model_name='externalsalesdata',
            name='daily_customers',
            field=models.IntegerField(default=0, verbose_name='日客流量'),
        ),
        migrations.AddField(
            model_name='externalsalesdata',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='是否已验证'),
        ),
        migrations.AddField(
            model_name='externalsalesdata',
            name='sync_batch_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='同步批次ID'),
        ),
        migrations.AddField(
            model_name='externalsalesdata',
            name='validation_errors',
            field=models.JSONField(blank=True, default=dict, verbose_name='验证错误信息'),
        ),
        migrations.AlterField(
            model_name='externalsalesdata',
            name='sync_status',
            field=models.CharField(choices=[('success', '同步成功'), ('failed', '同步失败'), ('pending', '等待同步'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='同步状态'),
        ),
        migrations.AddIndex(
            model_name='externalsalesdata',
            index=models.Index(fields=['sync_batch_id'], name='external_sa_sync_ba_fecc03_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsalesdata',
            index=models.Index(fields=['is_validated'], name='external_sa_is_vali_840099_idx'),
        ),
    ]
