# Generated by Django 4.2.7 on 2025-11-03 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('system', '系统消息'), ('approval_pending', '待审批提醒'), ('approval_approved', '审批通过'), ('approval_rejected', '审批拒绝'), ('milestone_reminder', '里程碑提醒'), ('contract_reminder', '合同提醒'), ('task_reminder', '任务提醒')], default='system', max_length=50, verbose_name='消息类型')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='message_recipie_2031b4_idx'), models.Index(fields=['recipient', 'created_at'], name='message_recipie_1e5818_idx'), models.Index(fields=['message_type'], name='message_message_4eeac1_idx')],
            },
        ),
    ]
