# Generated by Django 4.2.7 on 2025-11-03 02:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='点位名称')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='面积(㎡)')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='租金(元/月)')),
                ('status', models.CharField(choices=[('available', '可用'), ('following', '跟进中'), ('signed', '已签约'), ('abandoned', '已放弃')], default='available', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_locations', to='base_data.businessregion', verbose_name='业务大区')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '候选点位',
                'verbose_name_plural': '候选点位',
                'db_table': 'expansion_candidate_location',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='租金成本(元)')),
                ('decoration_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='装修成本(元)')),
                ('equipment_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='设备成本(元)')),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='其他成本(元)')),
                ('daily_sales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='日均销售额(元)')),
                ('monthly_sales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='月均销售额(元)')),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总投资(元)')),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='投资回报率(%)')),
                ('payback_period', models.IntegerField(verbose_name='回本周期(月)')),
                ('contribution_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='贡献率(%)')),
                ('formula_version', models.CharField(max_length=50, verbose_name='公式版本')),
                ('calculation_params', models.JSONField(default=dict, verbose_name='计算参数')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
            ],
            options={
                'verbose_name': '盈利测算',
                'verbose_name_plural': '盈利测算',
                'db_table': 'expansion_profit_calculation',
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='跟进单号')),
                ('status', models.CharField(choices=[('investigating', '调研中'), ('calculating', '测算中'), ('approving', '审批中'), ('signing', '签约中'), ('signed', '已签约'), ('abandoned', '已放弃')], default='investigating', max_length=20, verbose_name='跟进状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('survey_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='调研数据')),
                ('survey_date', models.DateField(blank=True, null=True, verbose_name='调研日期')),
                ('business_terms', models.JSONField(blank=True, default=dict, null=True, verbose_name='商务条件')),
                ('contract_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='合同信息')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('contract_reminders', models.JSONField(default=list, verbose_name='合同提醒')),
                ('is_abandoned', models.BooleanField(default=False, verbose_name='是否放弃')),
                ('abandon_reason', models.TextField(blank=True, verbose_name='放弃原因')),
                ('abandon_date', models.DateField(blank=True, null=True, verbose_name='放弃日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_records', to='base_data.legalentity', verbose_name='法人主体')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_records', to='store_expansion.candidatelocation', verbose_name='候选点位')),
                ('profit_calculation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_record', to='store_expansion.profitcalculation', verbose_name='盈利测算')),
            ],
            options={
                'verbose_name': '铺位跟进单',
                'verbose_name_plural': '铺位跟进单',
                'db_table': 'expansion_follow_up_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_no'], name='expansion_f_record__ab3a1b_idx'), models.Index(fields=['status'], name='expansion_f_status_a0025c_idx'), models.Index(fields=['priority'], name='expansion_f_priorit_62dc38_idx'), models.Index(fields=['location'], name='expansion_f_locatio_2047fd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidatelocation',
            index=models.Index(fields=['province', 'city', 'district'], name='expansion_c_provinc_0e756b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatelocation',
            index=models.Index(fields=['business_region', 'status'], name='expansion_c_busines_0b14c7_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatelocation',
            index=models.Index(fields=['status'], name='expansion_c_status_3557a8_idx'),
        ),
    ]
