# Generated by Django 4.2.7 on 2025-11-03 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='供应商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('supplier_type', models.CharField(choices=[('construction', '施工供应商'), ('equipment', '设备供应商'), ('material', '材料供应商'), ('other', '其他')], default='construction', max_length=20, verbose_name='供应商类型')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('legal_representative', models.CharField(blank=True, max_length=100, verbose_name='法定代表人')),
                ('status', models.CharField(choices=[('cooperating', '合作中'), ('stopped', '已停止')], default='cooperating', max_length=20, verbose_name='合作状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'base_supplier',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='主体名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='主体编码')),
                ('credit_code', models.CharField(max_length=50, unique=True, verbose_name='统一社会信用代码')),
                ('legal_representative', models.CharField(max_length=100, verbose_name='法定代表人')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('registered_address', models.TextField(blank=True, verbose_name='注册地址')),
                ('business_address', models.TextField(blank=True, verbose_name='经营地址')),
                ('status', models.CharField(choices=[('operating', '营运中'), ('cancelled', '已注销')], default='operating', max_length=20, verbose_name='营运状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '法人主体',
                'verbose_name_plural': '法人主体',
                'db_table': 'base_legal_entity',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='客户编码')),
                ('customer_type', models.CharField(choices=[('franchisee', '加盟商'), ('partner', '合作伙伴'), ('other', '其他')], default='franchisee', max_length=20, verbose_name='客户类型')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('credit_code', models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码')),
                ('legal_representative', models.CharField(blank=True, max_length=100, verbose_name='法定代表人')),
                ('cooperation_start_date', models.DateField(blank=True, null=True, verbose_name='合作开始日期')),
                ('cooperation_end_date', models.DateField(blank=True, null=True, verbose_name='合作结束日期')),
                ('status', models.CharField(choices=[('cooperating', '合作中'), ('terminated', '已终止')], default='cooperating', max_length=20, verbose_name='合作状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'base_customer',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='大区名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='大区编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('provinces', models.JSONField(default=list, verbose_name='关联省份列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_regions', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '业务大区',
                'verbose_name_plural': '业务大区',
                'db_table': 'base_business_region',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='预算名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='预算编码')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='预算总额')),
                ('budget_items', models.JSONField(default=dict, verbose_name='预算明细')),
                ('valid_from', models.DateField(verbose_name='生效日期')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='base_data.businessregion', verbose_name='适用大区')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '商务预算',
                'verbose_name_plural': '商务预算',
                'db_table': 'base_budget',
                'ordering': ['-valid_from', 'code'],
            },
        ),
    ]
