# Generated by Django 4.2.7 on 2025-11-03 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_data', '0001_initial'),
        ('store_expansion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='工程单号')),
                ('store_name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('design_files', models.JSONField(blank=True, default=list, verbose_name='设计图纸')),
                ('construction_start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('construction_end_date', models.DateField(blank=True, null=True, verbose_name='预计完工日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际完工日期')),
                ('status', models.CharField(choices=[('planning', '计划中'), ('in_progress', '施工中'), ('acceptance', '验收中'), ('rectification', '整改中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='工程状态')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='验收日期')),
                ('acceptance_result', models.CharField(choices=[('pending', '待验收'), ('passed', '验收通过'), ('failed', '验收不通过')], default='pending', max_length=20, verbose_name='验收结果')),
                ('acceptance_notes', models.TextField(blank=True, verbose_name='验收备注')),
                ('rectification_items', models.JSONField(blank=True, default=list, verbose_name='整改项')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_construction_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('follow_up_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_orders', to='store_expansion.followuprecord', verbose_name='关联跟进单')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_orders', to='base_data.supplier', verbose_name='施工供应商')),
            ],
            options={
                'verbose_name': '工程单',
                'verbose_name_plural': '工程单',
                'db_table': 'preparation_construction_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '已延期')], default='pending', max_length=20, verbose_name='状态')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='是否已发送提醒')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('construction_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='store_preparation.constructionorder', verbose_name='工程单')),
            ],
            options={
                'verbose_name': '工程里程碑',
                'verbose_name_plural': '工程里程碑',
                'db_table': 'preparation_milestone',
                'ordering': ['planned_date', 'id'],
                'indexes': [models.Index(fields=['construction_order', 'status'], name='preparation_constru_f66f74_idx'), models.Index(fields=['planned_date', 'status'], name='preparation_planned_60ec04_idx'), models.Index(fields=['status', 'reminder_sent'], name='preparation_status_e0d8a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_no', models.CharField(max_length=50, unique=True, verbose_name='清单编号')),
                ('store_name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('delivery_items', models.JSONField(blank=True, default=list, verbose_name='交付项')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='交付文档')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='交付状态')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交付日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('construction_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_checklist', to='store_preparation.constructionorder', verbose_name='关联工程单')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_checklists', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '交付清单',
                'verbose_name_plural': '交付清单',
                'db_table': 'preparation_delivery_checklist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checklist_no'], name='preparation_checkli_83b43d_idx'), models.Index(fields=['status'], name='preparation_status_bbb17c_idx'), models.Index(fields=['construction_order'], name='preparation_constru_bdd53f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='constructionorder',
            index=models.Index(fields=['order_no'], name='preparation_order_n_a92861_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionorder',
            index=models.Index(fields=['status'], name='preparation_status_79adf8_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionorder',
            index=models.Index(fields=['follow_up_record'], name='preparation_follow__3b4ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionorder',
            index=models.Index(fields=['construction_start_date'], name='preparation_constru_5b09df_idx'),
        ),
    ]
