/**
 * 权限常量定义
 */

// 系统管理权限
export const SYSTEM_PERMISSIONS = {
  // 部门管理
  DEPARTMENT_VIEW: 'system.department.view',
  DEPARTMENT_SYNC: 'system.department.sync',
  
  // 用户管理
  USER_VIEW: 'system.user.view',
  USER_MANAGE: 'system.user.manage',
  USER_SYNC: 'system.user.sync',
  
  // 角色管理
  ROLE_VIEW: 'system.role.view',
  ROLE_MANAGE: 'system.role.manage',
  
  // 审计日志
  AUDIT_VIEW: 'system.audit.view',
} as const;

// 权限组合
export const PERMISSION_GROUPS = {
  // 系统管理员权限组
  SYSTEM_ADMIN: [
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.DEPARTMENT_SYNC,
    SYSTEM_PERMISSIONS.USER_VIEW,
    SYSTEM_PERMISSIONS.USER_MANAGE,
    SYSTEM_PERMISSIONS.USER_SYNC,
    SYSTEM_PERMISSIONS.ROLE_VIEW,
    SYSTEM_PERMISSIONS.ROLE_MANAGE,
    SYSTEM_PERMISSIONS.AUDIT_VIEW,
  ],
  
  // 用户管理员权限组
  USER_ADMIN: [
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.USER_VIEW,
    SYSTEM_PERMISSIONS.USER_MANAGE,
    SYSTEM_PERMISSIONS.USER_SYNC,
  ],
  
  // 只读权限组
  READONLY: [
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.USER_VIEW,
    SYSTEM_PERMISSIONS.ROLE_VIEW,
    SYSTEM_PERMISSIONS.AUDIT_VIEW,
  ],
} as const;

// 权限描述
export const PERMISSION_DESCRIPTIONS = {
  [SYSTEM_PERMISSIONS.DEPARTMENT_VIEW]: '查看部门信息',
  [SYSTEM_PERMISSIONS.DEPARTMENT_SYNC]: '同步企业微信部门',
  [SYSTEM_PERMISSIONS.USER_VIEW]: '查看用户信息',
  [SYSTEM_PERMISSIONS.USER_MANAGE]: '管理用户（启用/停用、分配角色）',
  [SYSTEM_PERMISSIONS.USER_SYNC]: '同步企业微信用户',
  [SYSTEM_PERMISSIONS.ROLE_VIEW]: '查看角色信息',
  [SYSTEM_PERMISSIONS.ROLE_MANAGE]: '管理角色（创建、编辑、删除、配置权限）',
  [SYSTEM_PERMISSIONS.AUDIT_VIEW]: '查看审计日志',
} as const;

// 模块权限映射
export const MODULE_PERMISSIONS = {
  '系统管理': [
    SYSTEM_PERMISSIONS.DEPARTMENT_VIEW,
    SYSTEM_PERMISSIONS.DEPARTMENT_SYNC,
    SYSTEM_PERMISSIONS.USER_VIEW,
    SYSTEM_PERMISSIONS.USER_MANAGE,
    SYSTEM_PERMISSIONS.USER_SYNC,
    SYSTEM_PERMISSIONS.ROLE_VIEW,
    SYSTEM_PERMISSIONS.ROLE_MANAGE,
    SYSTEM_PERMISSIONS.AUDIT_VIEW,
  ],
} as const;