# Generated by Django 4.2.7 on 2025-11-03 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        ('store_preparation', '0001_initial'),
        ('store_expansion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(max_length=50, unique=True, verbose_name='门店编码')),
                ('store_name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('store_type', models.CharField(choices=[('standard', '标准店'), ('flagship', '旗舰店'), ('community', '社区店'), ('mall', '商场店')], max_length=50, verbose_name='门店类型')),
                ('operation_mode', models.CharField(choices=[('direct', '直营'), ('franchise', '加盟'), ('joint', '合营')], max_length=50, verbose_name='经营模式')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('construction', '施工中'), ('preparing', '筹备中'), ('operating', '营业中'), ('closed', '已闭店'), ('suspended', '暂停营业')], default='planning', max_length=20, verbose_name='门店状态')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='开业日期')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='闭店日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_stores', to=settings.AUTH_USER_MODEL, verbose_name='商务负责人')),
                ('business_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.businessregion', verbose_name='业务大区')),
                ('construction_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_preparation.constructionorder', verbose_name='关联工程单')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_profiles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('follow_up_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_expansion.followuprecord', verbose_name='关联跟进单')),
                ('store_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='店长')),
            ],
            options={
                'verbose_name': '门店档案',
                'verbose_name_plural': '门店档案',
                'db_table': 'store_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_code'], name='store_profi_store_c_7f0904_idx'), models.Index(fields=['store_name'], name='store_profi_store_n_f829f1_idx'), models.Index(fields=['status'], name='store_profi_status_325288_idx'), models.Index(fields=['business_region'], name='store_profi_busines_15387c_idx'), models.Index(fields=['created_at'], name='store_profi_created_0ebd15_idx')],
            },
        ),
    ]
